version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "2000:2000"
    volumes:
      - ./audio:/app/audio
      - ./script_cues.json:/app/script_cues.json
    networks:
      - theatre-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "1999:3000"
    depends_on:
      - backend
    networks:
      - theatre-network

networks:
  theatre-network:
    driver: bridge